// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjzhwknxpqatvrthjvue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqemh3a254cHFhdHZydGhqdnVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTI4MzgsImV4cCI6MjA1OTI2ODgzOH0.c80XOPVI1uTZEqV3Bk8Te3QJcTMD17OWHuSpdFvXynA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);